version: '3.8'

services:
  app:
    image: restaurant-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://database:5432/restaurantdb
      DB_USERNAME: postgres
      DB_PASSWORD: 1111
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: restaurantdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - "5432:5432"
